name: tide_monitoring
description: Monitoring
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.6.2
  flutter: ^3.27.4

dependencies:
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.2
  flutter:
    sdk: flutter
  injectable: ^2.5.0
  tide_di:
    path: ../tide_di

dev_dependencies:
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  tide_analysis:
    path: ../../utility/tide_analysis
