name: marvel_characters
description: List of Marvel characters
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.2
  flutter: ^3.27.4

dependencies:
  api_client:
    path: ../../utility/api_client
  tide_design_system:
    path: ../../utility/tide_design_system
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  injectable: ^2.5.0
  tide_monitoring:
    path: ../../utility/tide_monitoring
  tide_prelude:
    path: ../../utility/tide_prelude
  retrofit: ^4.4.2
  tide_di:
    path: ../../utility/tide_di

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9
  tide_analysis:
    path: ../../utility/tide_analysis
