name: tide_di
description: Tide's dependency injection mechanism
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:
  get_it: ^8.0.3

dev_dependencies:
  tide_analysis:
    path: ../tide_analysis
